/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const Root$schema = z.object({
  'wrapped': z.lazy(() => Wrapper$schema(z.string(), z.array(z.string()).readonly())),
  'recursive': z.lazy(() => Recursive$schema(z.number())),
})
const Box$schema = (type0$schema) => z.object({
  'value': type0$schema,
})
const Wrapper$schema = (type0$schema, type1$schema) => z.lazy(() => Box$schema(type1$schema))
const Recursive$schema = (type0$schema) => z.object({
  'value': type0$schema,
  'next': z.lazy(() => Recursive$schema(type0$schema)).optional(),
})

export const Root = Root$schema

export const TYPERT = {
  package: '@fixture/schema',
  face: 'host',
  schemas: [
    { name: 'Root', schema: Root },
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
