rm -f .git/dsh-lefthook-install.lock
env -u NODE_OPTIONS -u BASH_ENV \
  -u CODEBUDDY_SAFE_DELETE_ENABLED -u CODEBUDDY_SAFE_DELETE_BIN_DIR \
  -u CODEBUDDY_SAFE_DELETE_SHIM_DIR -u CODEBUDDY_SAFE_DELETE_REPORT_PATH \
  -u CODEBUDDY_SAFE_DELETE_BULK_GUARD -u CODEBUDDY_SAFE_DELETE_BULK_STATE_DIR \
  -u CODEBUDDY_SAFE_DELETE_BULK_THRESHOLD \
  ./build.sh
