/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const Root$schema = z.intersection(z.lazy(() => Base$schema), z.object({
  'current': z.number(),
}))
const Base$schema = z.object({
  'base': z.string(),
})

export const Root = Root$schema

export const TYPERT = {
  package: '@fixture/schema',
  face: 'host',
  schemas: [
    { name: 'Root', schema: Root },
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
