/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import type { z } from 'zod'
import type { Payload as Payload$source } from '@fixture/host'

export declare const Payload: z.ZodType<Payload$source>

export declare const TYPERT: unknown
