/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const Root$schema = z.object({
  'name': z.string().readonly(),
  'count': z.number().optional(),
})

export const Root = Root$schema

export const TYPERT = {
  package: '@fixture/schema',
  face: 'host',
  schemas: [
    { name: 'Root', schema: Root },
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
